ELearning/ELearning/Models/Login.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ELearning.Models
{
    public class Login
    {
        [Required(ErrorMessage = "Username is required")]
        [Display(Name = "Email")]
        public string Username { get; set; }

        [Required(ErrorMessage = "Password is required")]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Role is required")]
        [Display(Name = "Role")]
        public string UserRole { get; set; }
    }
}

ELearning/ELearning/Models/SignUpViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ELearning.Models
{
    public class SignUpViewModel
    {
        public string UserRole { get; set; }

        // Student properties
        [Display(Name = "Student Id")]
        public string sid { get; set; }

        [Required(ErrorMessage = "Student Name is required")]
        [Display(Name = "Student Name")]
        public string sname { get; set; }

        [Required(ErrorMessage = "Password is required")]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string spassword { get; set; }

        [Required(ErrorMessage = "Email is required")]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email")]
        public string semail { get; set; }
        [Required(ErrorMessage = "Interset is required")]
        [Display(Name = "Interset")]
        public string sInterset { get; set; }
        // Add other student-specific properties

        // Teacher properties
        [Display(Name = "Teacher Id")]
        public string tid { get; set; }

        [Required(ErrorMessage = "Teacher Name is required")]
        [Display(Name = "Teacher Name")]
        public string tname { get; set; }

        [Required(ErrorMessage = "Password is required")]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string tpassword { get; set; }

        [Required(ErrorMessage = "Email is required")]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email")]
        public string temail { get; set; }
        [Required(ErrorMessage = "Qualification is required")]
        [Display(Name = "Qualification")]
        public string tqualification { get; set; }
        // Add other teacher-specific properties
    }
}

ELearning/ELearning/Controllers/LoginSignupController.cs
using ELearning.Models;
using StuFeeWebApp.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace ELearning.Controllers
{
    public class LoginSignupController : Controller
    {
        // GET: LoginSignup
        DBAccess db = new DBAccess();
        public ActionResult Login()
        {
            ViewBag.HideHeader = true;
            return View();
        }
        [HttpPost]
        public ActionResult Login(Login user)
        {
            if(ModelState.IsValid)
            {
                db.OpenCon();
                if (user.UserRole == "Student")
                {             
                    string q = "Select * from student where s_email='" + user.Username + "' and s_password= '" + user.Password + "'";
                    db.cmd = new SqlCommand(q, db.con);
                    SqlDataReader sdr = db.cmd.ExecuteReader();
                    sdr.Read();
                    if (sdr.HasRows)
                    {
                        Session["sid"] = sdr[0].ToString();
                        Session["sname"] = sdr[1].ToString();
                        Session["semail"] = sdr[2].ToString();
                        Session["upassword"] = sdr[3].ToString();
                        Session["sinterest"] = sdr[4].ToString();
                        return RedirectToAction("Dashboard", "Student");
                    }
                    else
                    {
                        Response.Write("<script>alert('Invalid Student!');</script>");
                    }
                    sdr.Close();
                   

                }
                else if (user.UserRole == "Teacher")
                {
                    string q = "Select * from teacher where t_email='" + user.Username + "' and t_password= '" + user.Password + "'";
                    db.cmd = new SqlCommand(q, db.con);
                    SqlDataReader sdr = db.cmd.ExecuteReader();
                    sdr.Read();
                    if (sdr.HasRows)
                    {
                        Session["tid"] = sdr[0].ToString();
                        Session["tname"] = sdr[1].ToString();
                        Session["temail"] = sdr[3].ToString();
                        Session["tpassword"] = sdr[2].ToString();
                        Session["tq"] = sdr[4].ToString();
                        return RedirectToAction("Dashboard", "Teacher");
                    }
                    else
                    {
                        Response.Write("<script>alert('Invalid Teacher!');</script>");
                    }
                    sdr.Close();
                   
                }
                else if (user.UserRole == "Admin")
                {
                    string q = "Select * from admin where email='" + user.Username + "' and password= '" + user.Password + "'";
                    db.cmd = new SqlCommand(q, db.con);
                    SqlDataReader sdr = db.cmd.ExecuteReader();
                    sdr.Read();
                    if (sdr.HasRows)
                    {
                        Session["aid"] = sdr[0].ToString();
                        Session["aname"] = sdr[1].ToString();
                        Session["apassword"] = sdr[2].ToString();
                        Session["aemial"] = sdr[3].ToString();
                        return RedirectToAction("Dashboard", "Admin");

                    }
                    else
                    {
                        Response.Write("<script>alert('Invalid Admin!');</script>");
                    }
                    sdr.Close();
                  
                }
                db.CloseCon();
            }
            return View();
        }
       
        public ActionResult SignUp()
        {
            ViewBag.HideHeader = true;
            return View();
        }
        [HttpPost]
     
        public ActionResult SignUp(SignUpViewModel model)
        {
            
                db.OpenCon();
                if (model.UserRole == "Student")
                {
                    string q = "insert into Student values('" + model.sname + "','" + model.semail + "','" + model.spassword + "','" + model.sInterset + "','"+" "+"') ";
                    db.InsertUpdateDelete(q);
                    Response.Write("<script>alert('" + model.sname + " Registered!');</script>");
                }
                else if (model.UserRole == "Teacher")
                {

                    string q = "insert into teacher values('" + model.tname + "','" + model.tpassword + "','" + model.temail + "','" + model.tqualification + "') ";
                    db.InsertUpdateDelete(q);
                    Response.Write("<script>alert('" + model.tname + " Registered!');</script>");
                }
                db.CloseCon();

                return RedirectToAction("Login"); 
           
        }

    }
}

ELearning/ELearning/Views/LoginSignup/Login.cshtml
@model ELearning.Models.Login

@{
    ViewBag.Title = "Login";
}

<div class="container mt-5">
    <div class="row justify-content-center">
      
     
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Course Details</title>
            <!-- Bootstrap CSS -->
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
            <style>
                .header-title {
                    font-size: 3rem; /* Larger font size for impact */
                    font-weight: bold; /* Bold text for emphasis */
                    color: #007bff; /* Blue color */
                    text-shadow: 2px 2px 5px rgba(0, 0, 0, 0.1); /* Slight shadow for depth */
                    margin-bottom: 20px; /* Spacing below the header */
                }
            </style>
        </head>
        <body>
            <div class="container">
                <h1 class="text-center header-title">E-Learning</h1>
            </div>

            <!-- Bootstrap JS and dependencies -->
            <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        </body>

    <div class="col-md-10 col-lg-8">
        <div class="card shadow-sm">
            <div class="card-header text-center bg-primary text-white">
                <h4>Login</h4>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("Login", "LoginSignup", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()

                    <!-- Dropdown for user roles -->
                    <div class="form-group">
                        @Html.LabelFor(model => model.UserRole, new { @class = "control-label bold-label" })
                        @Html.DropDownListFor(model => model.UserRole,
                            new SelectList(new List<SelectListItem>
                            {
                                new SelectListItem { Text = "Admin", Value = "Admin" },
                                new SelectListItem { Text = "Teacher", Value = "Teacher" },
                                new SelectListItem { Text = "Student", Value = "Student" }
                            }, "Value", "Text"), "Select Role", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.UserRole, "", new { @class = "text-danger" })
                    </div>
                    <div class="row">

                        <!-- Username Field -->
                        <div class="col-md-12 col-lg-6 mb-3 mb-lg-0">
                            @Html.LabelFor(model => model.Username, new { @class = "control-label bold-label" })
                            @Html.TextBoxFor(model => model.Username, new { @class = "form-control", placeholder = "Enter your username" })
                            @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                        </div>

                        <!-- Sign Up Link -->
                        <div class="col-md-12 col-lg-6 d-flex align-items-center justify-content-center">
                            <div class="text-center">
                                @Html.Label("If you don't have an account? Sign Up!", new { @style = "font-size: 0.8em; color: #007bff;" })
                                <br />
                                <a href="@Url.Action("SignUp", "LoginSignup")" class="btn btn-primary mt-2">Sign Up</a>
                            </div>
                        </div>
                    </div>
                    <!-- Password Field -->
                    <div class="form-group">
                        @Html.LabelFor(model => model.Password, new { @class = "control-label bold-label" })
                        @Html.PasswordFor(model => model.Password, new { @class = "form-control", placeholder = "Enter your password" })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>

             


                    <!-- Login Button -->
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block">Login</button>
                    </div>
                }
            </div>
        </div>
    </div>
    </div>
</div>

ELearning/ELearning/Views/LoginSignup/SignUp.cshtml
@model ELearning.Models.SignUpViewModel

@{
    ViewBag.Title = "SignUp";
}
<br>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Course Details</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        .header-title {
            font-size: 3rem; /* Larger font size for impact */
            font-weight: bold; /* Bold text for emphasis */
            color: #007bff; /* Blue color */
            text-shadow: 2px 2px 5px rgba(0, 0, 0, 0.1); /* Slight shadow for depth */
            margin-bottom: 20px; /* Spacing below the header */
        }
    </style>
</head>
<body>
    <div class="container">
        <h1 class="text-center header-title">E-Learning</h1>
    </div>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-10 col-lg-8">
            <div class="card shadow-sm">
                <div class="card-header text-center bg-primary text-white">
                    <h4>SignUp</h4>
                </div>
                <div class="card-body">
                    @using (Html.BeginForm("SignUp", "LoginSignup", FormMethod.Post, new { id = "signUpForm" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-group">
                            @Html.Label("Role", new { @class = "control-label bold-label" })
                            @Html.DropDownList(
                                "UserRole",  // Name of the form element
                                new SelectList(new List<SelectListItem>
                                {
                                    new SelectListItem { Text = "Teacher", Value = "Teacher" },
                                    new SelectListItem { Text = "Student", Value = "Student" }
                                }, "Value", "Text"),
                                "Select Role",
                                new { @class = "form-control", id = "roleDropdown" }
                            )
                        </div>

                        <div id="dynamicContent">
                            <!-- Dynamic content will be loaded here based on role -->
                        </div>
                        @*
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary btn-block">SignUp</button>
                            </div>*@
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#roleDropdown').change(function () {
                var selectedRole = $(this).val();
                var dynamicContent = $('#dynamicContent');

                if (selectedRole === "Student") {
                    // Load Student form fields
                    dynamicContent.html(`
                                <h3>Student Form</h3>
                                <div class="form-group">
                                    <label for="sname">Student Name</label>
                                    <input type="text" name="sname" id="sname" class="form-control" />
                                </div>
                                <div class="form-group">
        <label for="semail">Email</label>
        <input type="text" name="semail" id="semail" class="form-control" />
</div>

                                <div class="form-group">
        <label for="spassword">Password</label>
        <input type="text" name="spassword" id="spassword" class="form-control" />
</div>
        <div class="form-group">
        <label for="sInterset">Interset</label>
        <input type="text" name="sInterset" id="sInterset" class="form-control" />
</div>
        <div class="form-group">
        <button type="submit" class="btn btn-primary btn-block">SignUp</button>
</div>
                                <!-- Add additional student-specific fields here -->
                            `);
                } else if (selectedRole === "Teacher") {
                    // Load Teacher form fields
                    dynamicContent.html(`
                                <h3>Teacher Form</h3>
                                                           <div class="form-group">
                                    <label for="tname">Teacher Name</label>
                                    <input type="text" name="tname" id="tname" class="form-control" />
                                </div>
                                <div class="form-group">
        <label for="temail">Email</label>
        <input type="text" name="temail" id="temail" class="form-control" />
</div>

                                <div class="form-group">
        <label for="tpassword">Password</label>
        <input type="text" name="tpassword" id="tpassword" class="form-control" />
</div>
        <div class="form-group">
        <label for="tqualification">Qualification</label>
        <input type="text" name="tqualification" id="tqualification" class="form-control" />
</div>
        <div class="form-group">
        <button type="submit" class="btn btn-primary btn-block">SignUp</button>
</div>
                                <!-- Add additional teacher-specific fields here -->
                            `);
                } else {
                    dynamicContent.empty();
                }
            });
        });
    </script>
}