ELearning/ELearning/Controllers/CourseController.cs
using ELearning.Models;
using StuFeeWebApp.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.Remoting.Messaging;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;

namespace ELearning.Controllers
{
    public class CourseController : Controller
    {
        DBAccess dbaobj = new DBAccess();
        // GET: Course
        public ActionResult CourseList()
        {
            ViewBag.HideHeader = true;
            List<Course> c = Course.CoursesList();

            return View(c);
        }

        [HttpGet]
        public ActionResult SearchCourses(string searchTerm)
        {
            List<Course> courses = new List<Course>();


            dbaobj.OpenCon();

            string query = "SELECT * FROM Course WHERE ('" + searchTerm + "' IS NULL OR c_title LIKE '%' + '" + searchTerm + "' + '%' OR c_keyword LIKE '%' + '" + searchTerm + "' + '%')";
            SqlCommand cmd = new SqlCommand(query, dbaobj.con);
            cmd.Parameters.AddWithValue(searchTerm, string.IsNullOrEmpty(searchTerm) ? (object)DBNull.Value : searchTerm);

            using (SqlDataReader reader = cmd.ExecuteReader())
            {
                while (reader.Read())
                {
                    var course = new Course
                    {
                        c_title = reader["c_title"].ToString(),
                        c_category = reader["c_category"].ToString(),
                        c_description = reader["c_description"].ToString(),
                        c_image = reader["c_image"].ToString(),
                        c_hours = Convert.ToInt32(reader["c_hours"]),
                        c_rating = Convert.ToInt32(reader["c_rating"])
                    };
                    courses.Add(course);
                }
            }
            dbaobj.CloseCon();


            return PartialView("_CourseTable", courses);
        }

        public ActionResult AddCousre()
        {
            ViewBag.HideHeader = true;
            return View();

        }
        [HttpPost]
        public ActionResult AddCousre(Course c)
        {
            ViewBag.HideHeader = true;

            if (ModelState.IsValid)
            {
                string ext = Path.GetExtension(c.ufile.FileName);
                string[] extarr = { ".png", ".PNG", ".jpg", ".bmp" };
                if (extarr.Contains(ext))
                {
                    string ufilename = c.c_title + ext;
                    string path = Path.Combine(Server.MapPath("/images"), ufilename);
                    c.ufile.SaveAs(path);
                    c.c_image = "/images/" + ufilename;
                    string q = "insert into course values('" + c.c_title + "','" + c.c_category + "','" + c.c_description + "','" + c.c_image + "','" + c.c_hours + "','" + c.c_rating + "','" + c.c_keyword + "') ";
                    dbaobj.InsertUpdateDelete(q);
                    Response.Write("<script>alert('" + c.c_title + " Registered!');</script>");
                    return RedirectToAction("CourseList");
                }
            }

            return View(c);
        }

        public ActionResult AssignCourseToTeacher()
        {
            ViewBag.HideHeader = true;
            List<SelectListItem> slist = new List<SelectListItem>();
            string s = "select tid,t_name from teacher";
            dbaobj.OpenCon();
            dbaobj.cmd = new SqlCommand(s, dbaobj.con);
            SqlDataReader sdr = dbaobj.cmd.ExecuteReader();
            while (sdr.Read())
            {
                slist.Add(new SelectListItem { Text = "" + sdr["t_name"].ToString() + "", Value = "" + sdr["tid"].ToString() + "" });
            }
            sdr.Close();
            dbaobj.CloseCon();
            TempData["tlist"] = slist;

            List<SelectListItem> clist = new List<SelectListItem>();
            string c = "select cid,c_title from Course";
            dbaobj.OpenCon();
            dbaobj.cmd = new SqlCommand(c, dbaobj.con);
            SqlDataReader sdr1 = dbaobj.cmd.ExecuteReader();
            while (sdr1.Read())
            {
                clist.Add(new SelectListItem { Text = "" + sdr1["c_title"].ToString() + "", Value = "" + sdr1["cid"].ToString() + "" });
            }
            sdr1.Close();
            dbaobj.CloseCon();
            TempData["clist"] = clist;


            return View();
        }
        [HttpPost]
        public ActionResult AssignCourseToTeacher(AllocateCourse a)
        {

            dbaobj.OpenCon();

            string q = "insert into Allocation values('" + a.TeacherId + "','" + a.CourseId + "') ";
            dbaobj.InsertUpdateDelete(q);

            dbaobj.CloseCon();
            return RedirectToAction("Dashboard", "Admin");
        }


        public ActionResult CourseDetails(int id)
        {
            ViewBag.HideHeader = true;
            Dictionary<int, bool> quizUploaded = new Dictionary<int, bool>();
            Dictionary<int, List<Tuple<string, string>>> pdfPaths = new Dictionary<int, List<Tuple<string, string>>>();
            Dictionary<int, List<Tuple<string, string>>> videoPaths = new Dictionary<int, List<Tuple<string, string>>>();
            Dictionary<int, bool> StudentResults = new Dictionary<int, bool>();


            dbaobj.OpenCon();

            for (int i = 1; i <= 16; i++)
            {
                // Initialize lists to store multiple PDFs and videos for each week
                List < Tuple<string, string> > pdfPathsForWeek = new List<Tuple<string, string>> ();
                List < Tuple<string, string> > videoPathsForWeek = new List<Tuple<string, string>>();

                // Query to get all PDFs for the current week
                string pdfQuery = "SELECT path,FileName FROM pdf WHERE cid = @cid AND weekNo = @weekNo";
                dbaobj.cmd = new SqlCommand(pdfQuery, dbaobj.con);
                dbaobj.cmd.Parameters.AddWithValue("@cid", id);
                dbaobj.cmd.Parameters.AddWithValue("@weekNo", i);
                SqlDataReader pdfReader = dbaobj.cmd.ExecuteReader();

                // Read all PDF paths for the week
                while (pdfReader.Read())
                {
                //    pdfPathsForWeek.Add(pdfReader["path"].ToString());
                    pdfPathsForWeek.Add(Tuple.Create(pdfReader["path"].ToString(), pdfReader["FileName"].ToString()));
                }
                pdfReader.Close();

                // Store the list of PDF paths and the upload status for the current week
                pdfPaths[i] = pdfPathsForWeek;

                // Query to get all video links for the current week
                string videoQuery = "SELECT videoPath,FileName FROM videos WHERE cid = @cid AND weekNo = @weekNo";
                dbaobj.cmd = new SqlCommand(videoQuery, dbaobj.con);
                dbaobj.cmd.Parameters.AddWithValue("@cid", id);
                dbaobj.cmd.Parameters.AddWithValue("@weekNo", i);
                SqlDataReader videoReader = dbaobj.cmd.ExecuteReader();

                // Read all video paths for the week
                while (videoReader.Read())
                {
              //      videoPathsForWeek.Add(videoReader["videoPath"].ToString());
                    videoPathsForWeek.Add(Tuple.Create(videoReader["videoPath"].ToString(), videoReader["FileName"].ToString()));
                }
                videoReader.Close();

                // Store the list of video paths for the current week
                videoPaths[i] = videoPathsForWeek;

                // Query to check if a quiz is uploaded for the current week
                string quizQuery = "SELECT COUNT(*) FROM Quiz WHERE cid = @cid AND weekNo = @weekNo";
                dbaobj.cmd = new SqlCommand(quizQuery, dbaobj.con);
                dbaobj.cmd.Parameters.AddWithValue("@cid", id);
                dbaobj.cmd.Parameters.AddWithValue("@weekNo", i);
                int quizCount = (int)dbaobj.cmd.ExecuteScalar();

                // Store the quiz upload status for the current week
                quizUploaded[i] = quizCount > 0;

                // Query to check students result for the current week
                string sr = "SELECT COUNT(*) FROM result WHERE cid = @cid AND weekNo = @weekNo";
                dbaobj.cmd = new SqlCommand(sr, dbaobj.con);
                dbaobj.cmd.Parameters.AddWithValue("@cid", id);
                dbaobj.cmd.Parameters.AddWithValue("@weekNo", i);
                int cs = (int)dbaobj.cmd.ExecuteScalar();
                StudentResults[i] = cs > 0;
            }

            dbaobj.CloseCon();

            // Pass the dictionaries to the view via ViewBag
            ViewBag.QuizUploaded = quizUploaded;  // Add this to pass quiz upload status
            ViewBag.PdfPaths = pdfPaths;
            ViewBag.VideoPaths = videoPaths;
            ViewBag.StudentResults = StudentResults;

            Course c = new Course();
            string q = "select * from Course where cid=@cid";
            dbaobj.OpenCon();
            dbaobj.cmd = new SqlCommand(q, dbaobj.con);
            dbaobj.cmd.Parameters.AddWithValue("@cid", id);
            SqlDataReader sdr1 = dbaobj.cmd.ExecuteReader();
            if (sdr1.Read())
            {
                c.cid = int.Parse(sdr1["cid"].ToString());
                c.c_title = sdr1["c_title"].ToString();
                c.c_category = sdr1["c_category"].ToString();
                c.c_description = sdr1["c_description"].ToString();
                c.c_image = sdr1["c_image"].ToString();
                c.c_hours = int.Parse(sdr1["c_hours"].ToString());
                c.c_rating = int.Parse(sdr1["c_rating"].ToString());
            }
            sdr1.Close();
            dbaobj.CloseCon();

            if (c == null)
            {
                return HttpNotFound();
            }

ELearning/ELearning/Controllers/TeacherController.cs
using ELearning.Models;
using StuFeeWebApp.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ELearning.Controllers
{
    public class TeacherController : Controller
    {
        // GET: Teacher
        DBAccess dbaobj=new DBAccess();
        public ActionResult DashBoard()
        {
            ViewBag.HideHeader = true;
            List<Course> courses = new List<Course>();
            List<Course> c = Course.CoursesList();
            List<AllocateCourse> a = AllocateCourse.AllocatedCourses();
            foreach (AllocateCourse aa in a) {
                if (Session["tid"].ToString() == aa.TeacherId.ToString()) 
                {
                    courses.Add(   c.Where(s => s.cid == aa.CourseId).First());
                }
                    }

            return View(courses);

        }
        public ActionResult TeacherList()
        {
            ViewBag.HideHeader = true;
            List<Teacher> teachers = Teacher.TeachersList();

            return View(teachers);

        }
        public ActionResult Logout()
        {
            Session.RemoveAll();
            return RedirectToAction("Login", "LoginSignup");
        }
    }
}

ELearning/ELearning/Views/Admin/DashBoard.cshtml
@{
    ViewBag.Title = "Admin Dashboard";
}

<div class="container mt-5">
    <div class="row mb-4">
        <div class="col-md-12 text-center">
            <h1 class="display-4">Admin Dashboard</h1>
        </div>
    </div>



    <div class="row justify-content-center">
        <!-- Teachers Button -->
        <div class="col-md-4">
            <div class="card shadow-sm mb-4">
                <div class="card-body text-center">
                    <h5 class="card-title"><i class="fas fa-chalkboard-teacher fa-2x"></i></h5>
                    <p class="card-text">Teachers</p>
                    <a href="@Url.Action("TeacherList", "Teacher")" class="btn btn-primary btn-block">Teachers</a>
                </div>
            </div>
        </div>

        <!-- Student Button -->
        <div class="col-md-4">
            <div class="card shadow-sm mb-4">
                <div class="card-body text-center">
                    <h5 class="card-title">
                        <i class="fas fa-user-graduate fa-2x"></i>
                    </h5>
                    <p class="card-text">Students</p>
                    <a href="@Url.Action("StudentList", "Student")" class="btn btn-primary btn-block">Students</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row justify-content-center">
        <!-- Courses Button -->
        <div class="col-md-4">
            <div class="card shadow-sm mb-4">
                <div class="card-body text-center">
                    <h5 class="card-title"><i class="fas fa-book fa-2x"></i></h5>
                    <p class="card-text">Courses</p>
                    <a href="@Url.Action("CourseList", "Course")" class="btn btn-primary btn-block">Courses</a>
                </div>
            </div>
        </div>

        <!-- Assign Course Button -->
        <div class="col-md-4">
            <div class="card shadow-sm mb-4">
                <div class="card-body text-center">
                    <h5 class="card-title"><i class="fas fa-tasks fa-2x"></i></h5>
                    <p class="card-text">Assign Courses to Teachers</p>
                    <a href="@Url.Action("AssignCourseToTeacher", "Course")" class="btn btn-primary btn-block">Assign Course</a>
                </div>
            </div>
        </div>
    </div>
    </div>
<br>
    <!-- Logout Button -->
<div class="text-center mb-1">
    <a class="btn btn-outline-danger" href="@Url.Action("Logout", "Teacher")">
        Logout <i class="fas fa-sign-out-alt"></i>
    </a>
</div>

    <!-- Include FontAwesome for Icons -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet" />
<style>
    .btn-outline-danger {
        border-width: 2px;
        transition: all 0.3s ease;
    }
</style>

    @*

        @Session["aid"]
        @Session["aname"]
        @Session["apassword"]
        @Session["aemial"]*@